name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: ["dev"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Teste cotacao_test
      run: coverage run -m cotacao_test

    - name: Relatorio
      run: coverage report

    - name: Git version
      uses: codacy/git-version@2.4.0
      
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
       image: oliviafarias/cotacaoimage
       tags: ${{github.run_number}}-prod
       registry: docker.io
       dockerfile: dockerfile
       username: ${{secrets.DOCKER_USERNAME}}
       password: ${{secrets.DOCKER_PASSWORD}}
